"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-01

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("price_cache",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("crop", sa.String(length=120), nullable=False),
    sa.Column("variety", sa.String(length=120), nullable=False),
    sa.Column("market", sa.String(length=120), nullable=False),
    sa.Column("district", sa.String(length=120), nullable=False),
    sa.Column("state", sa.String(length=120), nullable=False),
    sa.Column("date", sa.Date(), nullable=False),
    sa.Column("min_price", sa.Float(), nullable=False),
    sa.Column("max_price", sa.Float(), nullable=False),
    sa.Column("modal_price", sa.Float(), nullable=False),
    sa.Column("arrival_volume", sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_price_cache")),
    sa.UniqueConstraint("market", "crop", "variety", "date", name="uq_price_cache_key")
    )
    op.create_index(op.f("ix_price_cache_crop"), "price_cache", ["crop"], unique=False)
    op.create_index(op.f("ix_price_cache_date"), "price_cache", ["date"], unique=False)
    op.create_index(op.f("ix_price_cache_district"), "price_cache", ["district"], unique=False)
    op.create_index(op.f("ix_price_cache_market"), "price_cache", ["market"], unique=False)
    op.create_table("users",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("role", sa.String(length=20), nullable=False),
    sa.Column("name", sa.String(length=200), nullable=False),
    sa.Column("phone", sa.String(length=20), nullable=False),
    sa.Column("district", sa.String(length=120), nullable=False),
    sa.Column("taluka", sa.String(length=120), nullable=False),
    sa.Column("kyc_status", sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_users"))
    )
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)
    op.create_table("demands",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("buyer_id", sa.Integer(), nullable=False),
    sa.Column("crop", sa.String(length=120), nullable=False),
    sa.Column("quantity_kg", sa.Float(), nullable=False),
    sa.Column("quality_spec", sa.String(length=500), nullable=False),
    sa.Column("price_band_min", sa.Float(), nullable=False),
    sa.Column("price_band_max", sa.Float(), nullable=False),
    sa.Column("delivery_window", sa.String(length=120), nullable=False),
    sa.Column("status", sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(["buyer_id"], ["users.id"], name=op.f("fk_demands_buyer_id_users")),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_demands"))
    )
    op.create_table("lots",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("farmer_id", sa.Integer(), nullable=False),
    sa.Column("crop", sa.String(length=120), nullable=False),
    sa.Column("quantity_kg", sa.Float(), nullable=False),
    sa.Column("quality_grade", sa.String(length=50), nullable=False),
    sa.Column("photo_url", sa.String(length=500), nullable=True),
    sa.Column("expected_price", sa.Float(), nullable=False),
    sa.Column("available_from", sa.Date(), nullable=False),
    sa.Column("location", sa.String(length=120), nullable=False),
    sa.Column("status", sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(["farmer_id"], ["users.id"], name=op.f("fk_lots_farmer_id_users")),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_lots"))
    )
    op.create_table("matches",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("lot_id", sa.Integer(), nullable=False),
    sa.Column("demand_id", sa.Integer(), nullable=False),
    sa.Column("score", sa.Float(), nullable=False),
    sa.Column("status", sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(["demand_id"], ["demands.id"], name=op.f("fk_matches_demand_id_demands")),
    sa.ForeignKeyConstraint(["lot_id"], ["lots.id"], name=op.f("fk_matches_lot_id_lots")),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_matches"))
    )
    op.create_table("deals",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("match_id", sa.Integer(), nullable=False),
    sa.Column("agreed_price", sa.Float(), nullable=False),
    sa.Column("agreed_quantity", sa.Float(), nullable=False),
    sa.Column("logistics_mode", sa.String(length=30), nullable=False),
    sa.Column("payment_status", sa.String(length=20), nullable=False),
    sa.Column("pipeline_status", sa.String(length=30), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["match_id"], ["matches.id"], name=op.f("fk_deals_match_id_matches")),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_deals"))
    )
    op.create_table("offers",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("match_id", sa.Integer(), nullable=False),
    sa.Column("from_user_id", sa.Integer(), nullable=False),
    sa.Column("price", sa.Float(), nullable=False),
    sa.Column("quantity", sa.Float(), nullable=False),
    sa.Column("message", sa.String(length=1000), nullable=True),
    sa.Column("status", sa.String(length=20), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["from_user_id"], ["users.id"], name=op.f("fk_offers_from_user_id_users")),
    sa.ForeignKeyConstraint(["match_id"], ["matches.id"], name=op.f("fk_offers_match_id_matches")),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_offers"))
    )
    op.create_table("disputes",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("deal_id", sa.Integer(), nullable=False),
    sa.Column("raised_by", sa.Integer(), nullable=False),
    sa.Column("reason", sa.String(length=1000), nullable=False),
    sa.Column("status", sa.String(length=20), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["deal_id"], ["deals.id"], name=op.f("fk_disputes_deal_id_deals")),
    sa.ForeignKeyConstraint(["raised_by"], ["users.id"], name=op.f("fk_disputes_raised_by_users")),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_disputes"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("disputes")
    op.drop_table("offers")
    op.drop_table("deals")
    op.drop_table("matches")
    op.drop_table("lots")
    op.drop_table("demands")
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_price_cache_market"), table_name="price_cache")
    op.drop_index(op.f("ix_price_cache_district"), table_name="price_cache")
    op.drop_index(op.f("ix_price_cache_date"), table_name="price_cache")
    op.drop_index(op.f("ix_price_cache_crop"), table_name="price_cache")
    op.drop_table("price_cache")
    # ### end Alembic commands ###
